<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class DistrictSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()

    {
    
        DB::table('districts')->insert([
            [
                'district_name'=>'ລະມາມ',
                'district_name_e'=>'La Mam',
                'province_id'=>'1',
            ],[
                'district_name'=>'ດັກຈຶ່ງ',
                'district_name_e'=>'Dak Cheung',
                'province_id'=>'1',
            ],[
                'district_name'=>'ກະລຶມ',
                'district_name_e'=>'Kaleum',
                'province_id'=>'1',
            ],[
                'district_name'=>'ທ່າແຕ່ງ',
                'district_name_e'=>'Tha Teng',
                'province_id'=>'1',
            ],[
                'district_name'=>'ໄຊເສດຖາ',
                'district_name_e'=>'Saysetha',
                'province_id'=>'2',
            ]   ,[
                'district_name'=>'ສາມັກຄີໄຊ',
                'district_name_e'=>'Samakkixay',
                'province_id'=>'2',
            ],
            [
                'district_name'=>'ສະໜາມໄໍຊ',
                'district_name_e'=>'Sanamxay',
                'province_id'=>'2',
            ],
            [
                'district_name'=>'ສານໄຊ',
                'district_name_e'=>'Sanxay',
                'province_id'=>'2',
            ],
            [
                'district_name'=>'ພູວົງ',
                'district_name_e'=>'Phouvong',
                'province_id'=>'2',
            ],
            [
                'district_name'=>'ສາລະວັນ',
                'district_name_e'=>'Saravane',
                'province_id'=>'3',
            ],
            [
                'district_name'=>'ຕາໂອ້ຍ',
                'district_name_e'=>'Ta Oy',
                'province_id'=>'3',
            ],
            [
                'district_name'=>'ຕູ້ມລານ',
                'district_name_e'=>'Toumlane',
                'province_id'=>'3',
            ], [
                'district_name'=>'ລະຄອນເພັງ',
                'district_name_e'=>'Lakonepheng',
                'province_id'=>'3',
            ], [
                'district_name'=>'ວາປີ',
                'district_name_e'=>'Vapy',
                'province_id'=>'3',
            ], [
                'district_name'=>'ຄົງເຊໂດນ',
                'district_name_e'=>'Kongxedone  ',
                'province_id'=>'3',
            ], [
                'district_name'=>'ເລົ່າງາມ',
                'district_name_e'=>'Lao Ngam',
                'province_id'=>'3',
            ],
            [
                'district_name'=>'ສະມ້ວຍ',
                'district_name_e'=>'Sa Mouay',
                'province_id'=>'3',
            ],
            [
                'district_name'=>'ນະຄອນປາກເຊ',
                'district_name_e'=>'Pakse',
                'province_id'=>'4',
            ],
            [
                'district_name'=>'ຊະນະສົມບູນ',
                'district_name_e'=>'Sanasomboun',
                'province_id'=>'4',
            ],    [
                'district_name'=>'ບາຈຽງຈະເລີນສຸກ',
                'district_name_e'=>'Bachiengchaleunsouk',
                'province_id'=>'4',
            ],
            [
                'district_name'=>'ປາກຊ່ອງ',
                'district_name_e'=>'Paksong',
                'province_id'=>'4',
            ],
            [
                'district_name'=>'ປະທຸມພອນ',
                'district_name_e'=>'Phatoumphone',
                'province_id'=>'4',
            ],
            [
                'district_name'=>'ໂພນທອງ',
                'district_name_e'=>'Phonthong',
                'province_id'=>'4',
            ],
            [
                'district_name'=>'ຈຳປາສັກ',
                'district_name_e'=>'Champasak',
                'province_id'=>'4',
            ],
            [
                'district_name'=>'ສຸຂຸມມາ',
                'district_name_e'=>'Soukhoumma',
                'province_id'=>'4',
            ],
            [
                'district_name'=>'ມຸນລະປະໂມກ',
                'district_name_e'=>'Mounlapamok',
                'province_id'=>'4',
            ],
            [
                'district_name'=>'ໂຂງ',
                'district_name_e'=>'Kong',
                'province_id'=>'4',
            ],
            [
                'district_name'=>'ໄກສອນພົມວິຫານ',
                'district_name_e'=>'Kayson Phomvihane',
                'province_id'=>'5',
            ],
            [
                'district_name'=>'ອຸທຸມພອນ',
                'district_name_e'=>'Outhoumphone',
                'province_id'=>'5',
            ],
            [
                'district_name'=>'ອາດສະພັງທອງ',
                'district_name_e'=>'Atsaphangthong',
                'province_id'=>'5',
            ],
            [
                'district_name'=>'ພິນ',
                'district_name_e'=>'Phine',
                'province_id'=>'5',
            ],
            [
                'district_name'=>'ເຊໂປນ',
                'district_name_e'=>'Seponh',
                'province_id'=>'5',
            ],
            [
                'district_name'=>'ນອງ',
                'district_name_e'=>'Nong',
                'province_id'=>'5',
            ],
            [
                'district_name'=>'ທ່າປາງທອງ',
                'district_name_e'=>'Thapangthong',
                'province_id'=>'5',
            ],
            [
               'district_name'=>'ສອງຄອນ',
                'district_name_e'=>'Songkhone',
                'province_id'=>'5',
            ],
            [
                'district_name'=>'ຈຳພອນ',
                'district_name_e'=>'Champhone',
                'province_id'=>'5',
            ],
            [
                'district_name'=>'ຊົນບູລີ',
                'district_name_e'=>'Xonboury',
                'province_id'=>'5',
            ],
            [
                'district_name'=>'ໄຊບູລີ',
                'district_name_e'=>'Xayboury',
                'province_id'=>'5',
            ],
            [
                'district_name'=>'ວິລະບູລີ',
                'district_name_e'=>'Viraboury',
                'province_id'=>'5',
            ],
            [
                'district_name'=>'ອາດສະພອນ',
                'district_name_e'=>'Assaphone',
                'province_id'=>'5',
            ],
            [
                'district_name'=>'ໄຊພູທອງ',
                'district_name_e'=>'Xayphouthong',
                'province_id'=>'5',
            ],
            [
                'district_name'=>'ພະລານໄຊ',
                'district_name_e'=>'Phalanxay',
                'province_id'=>'5',
            ],
            [
                'district_name'=>'ທ່າແຂກ',
                'district_name_e'=>'Thakhek',
                'province_id'=>'6',
            ],
            [
                'district_name'=>'ມະຫາໄຊ',
                'district_name_e'=>'Mahaxay',
                'province_id'=>'6',
            ],
            [
                'district_name'=>'ໜອງບົກ',
                'district_name_e'=>'Nong Bok',
                'province_id'=>'6',
            ],
            [
                'district_name'=>'ຫີນບູນ',
                'district_name_e'=>'Hineboune',
                'province_id'=>'6',
            ],
            [
                'district_name'=>'ຍົມມະລາດ',
                'district_name_e'=>'Yommalath',
                'province_id'=>'6',
            ],
            [
                'district_name'=>'ບົວລະພາ',
                'district_name_e'=>'Boualapha',
                'province_id'=>'6',
            ],
            [
                'district_name'=>'ນາກາຍ',
                'district_name_e'=>'Nakai',
                'province_id'=>'6',
            ],
            [
                'district_name'=>'ເຊບັິງໄຟ',
                'district_name_e'=>'Sebangphay',
                'province_id'=>'6',
            ],
            [
                'district_name'=>'ໄຊບົວທອງ',
                'district_name_e'=>'Xaibouathong',
                'province_id'=>'6',
            ],
            [
                'district_name'=>'ຄູນຄຳ',
                'district_name_e'=>'Khounkham',
                'province_id'=>'6',
            ],
            [
                'district_name'=>'ປາກຊັນ',
                'district_name_e'=>'Pakxan',
                'province_id'=>'7',
            ],
            [
                'district_name'=>'ທ່າພະບາດ',
                'district_name_e'=>'Thaphabat',
                'province_id'=>'7',
            ],
            [
                'district_name'=>'ປາກກະດິງ',
                'district_name_e'=>'Pakkading',
                'province_id'=>'7',
            ],
            [
                'district_name'=>'ບໍລິຄັນ',
                'district_name_e'=>'Borikane',
                'province_id'=>'7',
            ],
            [
                'district_name'=>'ຄຳເກີດ',
                'district_name_e'=>'KhamKeut',
                'province_id'=>'7',
            ],
            [
                'district_name'=>'ວຽງທອງ',
                'district_name_e'=>'Viengthong',
                'province_id'=>'7',
            ],
            [
                'district_name'=>'ໄຊຈຳພອນ',
                'district_name_e'=>'Xaichamphone',
                'province_id'=>'7',
            ],
            [
                'district_name'=>'ວຽງຄຳ',
                'district_name_e'=>'Viengkham',
                'province_id'=>'8',
            ],
            [
                'district_name'=>'ໂພນໂຮງ',
                'district_name_e'=>'Phonhong',
                'province_id'=>'8',
            ],
            [
                'district_name'=>'ທຸລາຄົມ',
                'district_name_e'=>'Thoulakom',
                'province_id'=>'8',
            ],
            [
                'district_name'=>'ແກ້ວອຸດົມ',
                'district_name_e'=>'Keo Oudom',
                'province_id'=>'8',
            ],
            [
                'district_name'=>'ກາສີ',
                'district_name_e'=>'Kasy',
                'province_id'=>'8',
            ],
            [
                'district_name'=>'ວັງວຽງ',
                'district_name_e'=>'VangVieng',
                'province_id'=>'8',
            ],
            [
                'district_name'=>'ເຟືອງ',
                'district_name_e'=>'Feuang',
                'province_id'=>'8',
            ],
            [
                'district_name'=>'ຊະນະຄາມ',
                'district_name_e'=>'Xanakham',
                'province_id'=>'8',
            ],
            [
                'district_name'=>'ແມດ',
                'district_name_e'=>'Mad',
                'province_id'=>'8',
            ],

            [
                'district_name'=>'ຫີນເຫີບ',
                'district_name_e'=>'Hinhurp',
                'province_id'=>'8',
            ],
            [
                'district_name'=>'ຮົ່ມ',
                'district_name_e'=>'Hom',
                'province_id'=>'8',
            ],
            [
                'district_name'=>'ໄຊສົມບູນ',
                'district_name_e'=>'Xaysomboun',
                'province_id'=>'8',
            ],
            [
                'district_name'=>'ໝື່ນ',
                'district_name_e'=>'Meun',
                'province_id'=>'8',
            ],
            [
                'district_name'=>'ຈັນທະບູລີ',
                'district_name_e'=>'Chanthabuly',
                'province_id'=>'9',
            ],
            [
                'district_name'=>'ສີໂຄດຕະບອງ',
                'district_name_e'=>'Sikhottabog',
                'province_id'=>'9',
            ],
            [
                'district_name'=>'ໄຊເສດຖາ',
                'district_name_e'=>'Xaysetha',
                'province_id'=>'9',
            ],       [
                'district_name'=>'ສີສັດຕະນາກ',
                'district_name_e'=>'Sisattanak',
                'province_id'=>'9',
            ],       [
                'district_name'=>'ນາຊາຍທອງ',
                'district_name_e'=>'Naxaithong',
                'province_id'=>'9',
            ], [
                'district_name'=>'ໄຊທານີ',
                'district_name_e'=>'Xaythany',
                'province_id'=>'9',
            ],
            [
                'district_name'=>'ຫາດຊາຍຟອງ',
                'district_name_e'=>'Hadxayfong',
                'province_id'=>'9',
            ],
            [
                'district_name'=>'ສັງທອງ',
                'district_name_e'=>'Sangthong',
                'province_id'=>'9',
            ],
            [
                'district_name'=>'ປາກງື່ມ',
                'district_name_e'=>'Parkngum',
                'province_id'=>'9',
            ],
            [
                'district_name'=>'ຫຼວງພະບາງ',
                'district_name_e'=>'Luangprabang',
                'province_id'=>'10',
            ],
            [
                'district_name'=>'ຊຽງເງິນ',
                'district_name_e'=>'Xiengngeun',
                'province_id'=>'10',
            ],    [
                'district_name'=>'ນານ',
                'district_name_e'=>'Nane',
                'province_id'=>'10',
            ],
            [
                'district_name'=>'ປາກອູ',
                'district_name_e'=>'Pak Ou',
                'province_id'=>'10',
            ],       [
                'district_name'=>'ນ້ຳບາກ',
                'district_name_e'=>'Nam bak',
                'province_id'=>'10',
            ],       [
                'district_name'=>'ງອຍ',
                'district_name_e'=>'Ngoy',
                'province_id'=>'10',
            ],       [
                'district_name'=>'ປາກແຊງ',
                'district_name_e'=>'Pak Seng',
                'province_id'=>'10',
            ],       [
                'district_name'=>'ໂພນໄຊ',
                'district_name_e'=>'Phonxay',
                'province_id'=>'10',
            ],
            [
                'district_name'=>'ຈອມເພັດ',
                'district_name_e'=>'Chomphet',
                'province_id'=>'10',
            ],       [
                'district_name'=>'ວຽງຄຳ',
                'district_name_e'=>'Viengkham',
                'province_id'=>'10',
            ],       [
                'district_name'=>'ຄູນ',
                'district_name_e'=>'Koun',
                'province_id'=>'10',
            ],       [
                'district_name'=>'ໂພນທອງ',
                'district_name_e'=>'Phonthong',
                'province_id'=>'10',
            ],
            [
                'district_name'=>'ຫຼວງນໍ້ຳທາ',
                'district_name_e'=>'Luangnamtha',
                'province_id'=>'11',
            ],
            [
                'district_name'=>'ເມືອງສິງ',
                'district_name_e'=>'Sing',
                'province_id'=>'11',
            ],
            [
                'district_name'=>'ລອງ',
                'district_name_e'=>'Long',
                'province_id'=>'11',
            ],
            [
                'district_name'=>'ວຽງພູຄາ',
                'district_name_e'=>'Viengphoukha',
                'province_id'=>'11',
            ],
            [
                'district_name'=>'ນາແລ',
                'district_name_e'=>'Na le',
                'province_id'=>'11',
            ],
            [
                'district_name'=>'ໄຊຍະບູລີ',
                'district_name_e'=>'Sainyabuli',
                'province_id'=>'12',
            ],
            [
                'district_name'=>'ຄອບ',
                'district_name_e'=>'Khop',
                'province_id'=>'12',
            ],
            [
                'district_name'=>'ຫົງສາ',
                'district_name_e'=>'Hongsa',
                'province_id'=>'12',
            ],
            [
                'district_name'=>'ເງິນ',
                'district_name_e'=>'Ngeun',
                'province_id'=>'12',
            ],
            [
                'district_name'=>'ຊຽງຮ່ອນ',
                'district_name_e'=>'Xienghone',
                'province_id'=>'12',
            ],
            [
                'district_name'=>'ພຽງ',
                'district_name_e'=>'Phiang',
                'province_id'=>'12',
            ],
            [
                'district_name'=>'ປາກລາຍ',
                'district_name_e'=>'Parklai',
                'province_id'=>'12',
            ],
            [
                'district_name'=>'ແກນທ້າວ',
                'district_name_e'=>'Kenethao',
                'province_id'=>'12',
            ],
            [
                'district_name'=>'ບໍ່ແຕນ',
                'district_name_e'=>'Botene',
                'province_id'=>'12',
            ],
            [
                'district_name'=>'ທົ່ງມີໄຊ',
                'district_name_e'=>'Thongmyxay',
                'province_id'=>'12',
            ],
            [
                'district_name'=>'ໄຊສະຖານ',
                'district_name_e'=>'Xaisathan',
                'province_id'=>'12',
            ],
            [
                'district_name'=>'ຜົ້ງສາລີ',
                'district_name_e'=>'Phongsaly',
                'province_id'=>'13',
            ],   [
                'district_name'=>'ໃໝ່',
                'district_name_e'=>'May',
                'province_id'=>'13',
            ],
            [
                'district_name'=>'ຂວາ',
                'district_name_e'=>'Khoua',
                'province_id'=>'13',
            ],
            [
                'district_name'=>'ສຳພັນ',
                'district_name_e'=>'Samphanh',
                'province_id'=>'13',
            ],
            [
                'district_name'=>'ບຸນເໜືອ',
                'district_name_e'=>'Boun Neua',
                'province_id'=>'13',
            ],
            [
                'district_name'=>'ຍອດອູ',
                'district_name_e'=>'Yot Ou',
                'province_id'=>'13',
            ],
            [
                'district_name'=>'ບຸນໃຕ້',
                'district_name_e'=>'Boun Tay',
                'province_id'=>'13',
            ],
            [
                'district_name'=>'ແປກ',
                'district_name_e'=>'Pek',
                'province_id'=>'14',
            ],
            [
                'district_name'=>'ຄຳ',
                'district_name_e'=>'Kham',
                'province_id'=>'14',
            ],
            [
                'district_name'=>'ໜອງແຮດ',
                'district_name_e'=>'Nong Het',
                'province_id'=>'14',
            ],
            [
                'district_name'=>'ຄູນ',
                'district_name_e'=>'Khoune',
                'province_id'=>'14',
            ],
            [
                'district_name'=>'ໝອກ',
                'district_name_e'=>'Mok',
                'province_id'=>'14',
            ],
            [
                'district_name'=>'ພູກູດ',
                'district_name_e'=>'Phou Kout',
                'province_id'=>'14',
            ],
            [
                'district_name'=>'ຜາໄຊ',
                'district_name_e'=>'Phaxay',
                'province_id'=>'14',
            ],
            [
                'district_name'=>'ທ່າໂທມ',
                'district_name_e'=>'Thathom',
                'province_id'=>'14',
            ],
            [
                'district_name'=>'ຊຳເໜືອ',
                'district_name_e'=>'Xam Neua',
                'province_id'=>'15',
            ],
            [
                'district_name'=>'ຊຽງຄໍ້',
                'district_name_e'=>'XiengKho',
                'province_id'=>'15',
            ],
            [
                'district_name'=>'ວຽງທອງ',
                'district_name_e'=>'Hiam',
                'province_id'=>'15',
            ],
            [
                'district_name'=>'ຫົວເມືອງ',
                'district_name_e'=>'Houameuang',
                'province_id'=>'15',
            ],
            [
                'district_name'=>'ຊຳໃຕ້',
                'district_name_e'=>'Samtay',
                'province_id'=>'15',
            ],
            [
                'district_name'=>'ສົບເບົາ',
                'district_name_e'=>'Sop Bao',
                'province_id'=>'15',
            ],
            [
                'district_name'=>'ແອດ',
                'district_name_e'=>'Et',
                'province_id'=>'15',
            ],
            [
                'district_name'=>'ກວນ',
                'district_name_e'=>'Kone',
                'province_id'=>'15',
            ],
            [
                'district_name'=>'ວຽງໄຊ',
                'district_name_e'=>'Viengxay',
                'province_id'=>'15',
            ],
            [
                'district_name'=>'ໄຊ',
                'district_name_e'=>'Xay',
                'province_id'=>'16',
            ],
            [
                'district_name'=>'ຫຼາ',
                'district_name_e'=>'La',
                'province_id'=>'16',
            ],
            [
                'district_name'=>'ນາໝໍ້',
                'district_name_e'=>'Na Mo',
                'province_id'=>'16',
            ],
            [
                'district_name'=>'ງາ',
                'district_name_e'=>'Nga',
                'province_id'=>'16',
            ],
            [
                'district_name'=>'ແບ່ງ',
                'district_name_e'=>'Beng',
                'province_id'=>'16',
            ],
            [
                'district_name'=>'ຮຸນ',
                'district_name_e'=>'Houne',
                'province_id'=>'16',
            ],
            [
                'district_name'=>'ປາກແບ່ງ',
                'district_name_e'=>'Pak Beng',
                'province_id'=>'16',
            ],
            [
                'district_name'=>'ເຂດພິເສດນ້ຳຍູ້',
                'district_name_e'=>'Nam Ngou',
                'province_id'=>'17',
            ],
            [
                'district_name'=>'ຫ້ວຍຊາຍ',
                'district_name_e'=>'Houaxay',
                'province_id'=>'17',
            ],
            [
                'district_name'=>'ຕົ້ນເຜິ້ງ',
                'district_name_e'=>'Ton Pheung',
                'province_id'=>'17',
            ],
            [
                'district_name'=>'ເມິງ',
                'district_name_e'=>'Meung',
                'province_id'=>'17',
            ],
            [
                'district_name'=>'ຜາອຸດົມ',
                'district_name_e'=>'Pha Oudom',
                'province_id'=>'17',
            ],
            [
                'district_name'=>'ປາກທາ',
                'district_name_e'=>'Pak Tha',
                'province_id'=>'17',
            ],
            [
                'district_name'=>'ຮົ່ມ',
                'district_name_e'=>'Hom',
                'province_id'=>'18',
            ],
            [
                'district_name'=>'ທ່າໂທມ',
                'district_name_e'=>'Thathom',
                'province_id'=>'18',
            ],
            [
                'district_name'=>'ອະນຸວົງ',
                'district_name_e'=>'Anouvong',
                'province_id'=>'18',
            ],
            [
                'district_name'=>'ລ່ອງຊານ',
                'district_name_e'=>'Longxan',
                'province_id'=>'18',
            ],
            [
                'district_name'=>'ລ່ອງແຈ້ງ',
                'district_name_e'=>'Longchaeng',
                'province_id'=>'18',
            ],
        ]);
    }
}
